import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { GradeSheet, Grade } from '../types';

/**
 * Calculate letter grade based on percentage
 */
export function calculateLetterGrade(percentage: number): 'A' | 'B' | 'C' | 'D' | 'F' {
    if (percentage >= 90) return 'A';
    if (percentage >= 80) return 'B';
    if (percentage >= 70) return 'C';
    if (percentage >= 60) return 'D';
    return 'F';
}

/**
 * Calculate statistics for a set of grades
 */
export function calculateStatistics(grades: Grade[]) {
    const total = grades.length;

    if (total === 0) {
        return {
            total: 0,
            passed: 0,
            failed: 0,
            passRate: 0,
            average: 0,
            highest: 0,
            lowest: 0
        };
    }

    const passed = grades.filter(g => g.percentage >= 60).length;
    const failed = total - passed;
    const passRate = Math.round((passed / total) * 100);

    const percentages = grades.map(g => g.percentage);
    const average = Math.round(percentages.reduce((a, b) => a + b, 0) / total);
    const highest = Math.max(...percentages);
    const lowest = Math.min(...percentages);

    return { total, passed, failed, passRate, average, highest, lowest };
}

/**
 * Export gradesheet to Excel with professional formatting
 */
export function exportToExcel(gradeSheet: GradeSheet): void {
    const workbook = XLSX.utils.book_new();

    // Prepare data with a header section
    const data: any[] = [
        ['OFFICIAL GRADE REPORT'],
        ['Generated By E-WRITTEN'],
        [''], // Spacer
        ['Course Code', gradeSheet.courseCode],
        ['Course Name', gradeSheet.courseName],
        ['Exam Title', gradeSheet.examTitle],
        ['Date Generated', new Date().toLocaleDateString()],
        [''], // Spacer
    ];

    // Headers for the table
    const tableHeaders = ['#', 'Student ID', 'Student Name', 'Score', 'Max Score', 'Percentage', 'Letter Grade', 'Status'];
    data.push(tableHeaders);

    // Grade Rows
    gradeSheet.grades.forEach((g, index) => {
        data.push([
            index + 1,
            g.studentId,
            g.studentName,
            g.score,
            g.maxScore,
            g.percentage + '%',
            g.letterGrade,
            g.status.toUpperCase()
        ]);
    });

    const worksheet = XLSX.utils.aoa_to_sheet(data);

    // Set Column Widths for readability
    worksheet['!cols'] = [
        { wch: 5 },  // #
        { wch: 15 }, // ID
        { wch: 30 }, // Name
        { wch: 10 }, // Score
        { wch: 10 }, // Max
        { wch: 12 }, // %
        { wch: 12 }, // Grade
        { wch: 15 }  // Status
    ];

    XLSX.utils.book_append_sheet(workbook, worksheet, 'Grade Report');

    // Stats Sheet
    const stats = gradeSheet.statistics;
    const statsData = [
        ['PERFORMANCE STATISTICS'],
        [''],
        ['Metric', 'Value'],
        ['Total Students', stats.total],
        ['Passed', stats.passed],
        ['Failed', stats.failed],
        ['Pass Rate', stats.passRate + '%'],
        ['Average Score', stats.average + '%'],
        ['Highest Score', stats.highest + '%'],
        ['Lowest Score', stats.lowest + '%']
    ];

    const statsSheet = XLSX.utils.aoa_to_sheet(statsData);
    statsSheet['!cols'] = [{ wch: 20 }, { wch: 15 }];

    XLSX.utils.book_append_sheet(workbook, statsSheet, 'Analytics');

    // Download
    const fileName = `${gradeSheet.courseCode}_${gradeSheet.examTitle.replace(/\s+/g, '_')}_Report.xlsx`;
    XLSX.writeFile(workbook, fileName);
}

/**
 * Export gradesheet to PDF with professional styling
 */
export function exportToPDF(gradeSheet: GradeSheet): void {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const stats = gradeSheet.statistics;

    // --- Header Section ---
    // University/Department Header
    doc.setFillColor(76, 29, 149); // Violet-900 (Main Brand Color)
    doc.rect(0, 0, pageWidth, 40, 'F'); // Top banner

    // Title Text (White)
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('OFFICIAL GRADE REPORT', 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('FACULTY OF COMMERCE - BIS PROGRAM', 14, 28);

    // Right side Header Info (White)
    doc.setFontSize(10);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 14, 20, { align: 'right' });
    doc.text('CONFIDENTIAL', pageWidth - 14, 28, { align: 'right' });


    // --- Context Section ---
    doc.setTextColor(30, 41, 59); // Slate-800
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');

    let yPos = 55;
    doc.text(`Course: ${gradeSheet.courseCode} - ${gradeSheet.courseName}`, 14, yPos);
    doc.text(`Exam: ${gradeSheet.examTitle}`, 14, yPos + 7);

    // Exam Metrics Summary Box
    doc.setDrawColor(226, 232, 240); // Slate-200
    doc.setFillColor(248, 250, 252); // Slate-50
    doc.roundedRect(pageWidth - 90, 46, 76, 24, 2, 2, 'FD');

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139); // Slate-500

    doc.text('Total Students', pageWidth - 85, 52);
    doc.text('Pass Rate', pageWidth - 55, 52);
    doc.text('Average', pageWidth - 25, 52);

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59); // Slate-800
    doc.setFontSize(12);
    doc.text(stats.total.toString(), pageWidth - 85, 60);

    // Pass Rate Color
    if (stats.passRate >= 70) doc.setTextColor(21, 128, 61); // Green
    else doc.setTextColor(190, 18, 60); // Red
    doc.text(`${stats.passRate}%`, pageWidth - 55, 60);

    doc.setTextColor(30, 41, 59); // Back to Slate
    doc.text(`${stats.average}%`, pageWidth - 25, 60);

    // --- Table Section ---
    autoTable(doc, {
        startY: 80,
        head: [['#', 'Student ID', 'Student Name', 'Score', 'Max', '%', 'Grade', 'Status']],
        body: gradeSheet.grades.map((g, index) => [
            index + 1,
            g.studentId,
            g.studentName,
            g.score,
            g.maxScore,
            g.percentage + '%',
            g.letterGrade,
            g.status.toUpperCase()
        ]),
        styles: {
            fontSize: 10,
            cellPadding: 4,
            lineColor: [226, 232, 240], // Slate-200
            lineWidth: 0.1,
        },
        headStyles: {
            fillColor: [76, 29, 149], // Violet-900
            textColor: 255,
            fontStyle: 'bold',
            halign: 'center'
        },
        columnStyles: {
            0: { cellWidth: 10, halign: 'center' },
            1: { cellWidth: 30 },
            2: { cellWidth: 'auto' }, // Name takes remaining space
            3: { cellWidth: 15, halign: 'center' },
            4: { cellWidth: 15, halign: 'center' },
            5: { cellWidth: 15, halign: 'center', fontStyle: 'bold' },
            6: { cellWidth: 15, halign: 'center', fontStyle: 'bold' },
            7: { cellWidth: 25, halign: 'center' }
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252] // Slate-50
        },
        margin: { top: 80 },
        didParseCell: function (data) {
            // Color code grades
            if (data.section === 'body' && data.column.index === 6) {
                const grade = data.cell.raw;
                if (grade === 'A') data.cell.styles.textColor = [21, 128, 61]; // Green
                else if (grade === 'F') data.cell.styles.textColor = [190, 18, 60]; // Red
            }
        }
    });

    // --- Signature Section ---
    const finalY = (doc as any).lastAutoTable.finalY || 200;

    // Check if we need a new page for signatures
    if (finalY > pageHeight - 50) {
        doc.addPage();
        yPos = 40;
    } else {
        yPos = finalY + 40;
    }

    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);

    // Examiner Signature
    doc.line(14, yPos, 80, yPos);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    doc.text("Course Instructor / Examiner", 14, yPos + 5);

    // Head of Department Signature
    doc.line(pageWidth - 80, yPos, pageWidth - 14, yPos);
    doc.text("Head of Department", pageWidth - 80, yPos + 5);

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `System Generated Report - E-WRITTEN - Page ${i} of ${pageCount}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
    }

    // Save
    const fileName = `${gradeSheet.courseCode}_${gradeSheet.examTitle.replace(/\s+/g, '_')}_Official_Report.pdf`;
    doc.save(fileName);
}

/**
 * Prepare gradesheet from grades
 */
export function prepareGradeSheet(
    examId: string,
    examTitle: string,
    courseCode: string,
    courseName: string,
    grades: Grade[]
): GradeSheet {
    const statistics = calculateStatistics(grades);

    return {
        examId,
        examTitle,
        courseCode,
        courseName,
        grades: grades.sort((a, b) => a.studentName.localeCompare(b.studentName)),
        statistics
    };
}
