import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface Translations {
    [key: string]: {
        [key: string]: string;
    };
}

const translations: Translations = {
    en: {
        // Sidebar
        'overview': 'Overview',
        'profile': 'Profile',
        'exams': 'Exams',
        'my_courses': 'My Courses',
        'students': 'Students',
        'settings': 'Settings',
        'sign_out': 'Sign Out',
        'smart_grader': 'E-WRITTEN',
        'faculty_space': 'Faculty Space',
        'main': 'Main',
        'academic': 'Academic',
        'account': 'Account',

        // Dashboard Home
        'academic_dashboard': 'Academic Dashboard',
        'welcome_back': 'Welcome back, Doctor.',
        'active_courses': 'Active Courses',
        'total_students': 'Total Students',
        'pending_papers': 'Pending Papers',
        'graded_this_week': 'Graded This Week',
        'average_grade': 'Average Grade',
        'grade_distribution': 'Grade Distribution',
        'pass_fail_analysis': 'Pass vs. Fail Analysis',
        'passed': 'Passed',
        'failed': 'Failed',
        'view_all': 'View All',
        'academic_year': 'Academic Year 2025-2026',
        'welcome_back_name': 'Welcome back,',
        'dashboard_title': 'Dashboard',
        'active_exams': 'Active Exams',
        'new_grades': 'New Grades',
        'avg_score': 'Avg Score',
        'at_risk': 'At Risk',
        'overall_performance_curve': 'Overall performance curve',
        'pass_fail_ratio': 'Pass vs. Fail Ratio',
        'pass_rate': 'Pass Rate',
        'no_description': 'No description provided.',
        'credits': 'Credits',
        'students_count': 'Students',
 
        // Settings
        'settings_title': 'Settings & Preferences',
        'settings_subtitle': 'Customize your workspace to fit your needs.',
        'appearance': 'Appearance',
        'theme': 'Theme',
        'light': 'Light',
        'dark': 'Dark',
        'system': 'System',
        'accessibility': 'Accessibility',
        'font_size': 'Font Size',
        'high_contrast': 'High Contrast Mode',
        'reduced_motion': 'Reduced Motion',
        'language_region': 'Language & Region',
        'notifications': 'Notifications',
        'security': 'Security & Login',
        'change_password': 'Change Password',
        'danger_zone': 'Danger Zone',
        'email_notifications': 'Email Notifications',
        'push_notifications': 'Push Notifications',

        // Exams Management
        'back_to_overview': 'Back to Overview',
        'examinations': 'Examinations',
        'exams_manager': 'Exams Manager',
        'exams_subtitle': 'Schedule, manage, and track all your course assessments in one place.',
        'create_new_exam': 'Create New Exam',
        'total_exams': 'Total Exams',
        'upcoming': 'Upcoming',
        'completed': 'Completed',
        'with_model_answers': 'With Model Answers',
        'search_exams_placeholder': 'Search by exam title, course code...',
        'all_types': 'All Types',
        'midterm': 'Midterm',
        'final': 'Final',
        'quiz': 'Quiz',
        'assignment': 'Assignment',
        'model_answer_attached': 'Model Answer Attached',
        'no_model_answer': 'No Model Answer',
        'view_details': 'View Details',
        'draft': 'Draft',
        'scheduled': 'Scheduled',
        'ongoing': 'Ongoing',
        'graded': 'Graded',
        'pending': 'Pending',
        'processing': 'Processing',
        'no_exams_found': 'No exams found',
        'no_exams_created': 'No exams created yet',
        'no_exams_found_desc': "We couldn't find any exams matching your current filters. Try adjusting your search or filter settings.",
        'no_exams_created_desc': 'Get started by creating your first exam. You can set up details, duration, and later upload model answers.',
        'create_first_exam': 'Create First Exam',

        // Create Exam Modal
        'create_exam_subtitle': 'Set up exam details and upload model answer later',
        'course_label': 'Course *',
        'select_course_placeholder': 'Select a course',
        'exam_title_label': 'Exam Title *',
        'exam_title_placeholder': 'e.g., Midterm Exam - Fall 2026',
        'exam_type_label': 'Exam Type *',
        'exam_date_label': 'Exam Date & Time *',
        'exam_duration_label': 'Duration (minutes) *',
        'exam_marks_label': 'Total Marks *',
        'multi_page_label': 'Multi-page Exam',
        'cancel': 'Cancel',
        'create_exam_button': 'Create Exam',
        'exam_date_future_error': 'Exam date must be in the future',
        'fill_required_error': 'Please fill in all required fields',

        // Exam Detail
        'back_to_exams': 'Back to Exams',
        'view_results': 'View Results',
        'model_answer_rubric': 'Model Answer / Grading Rubric',
        'text_mode': 'Text',
        'pdf_mode': 'PDF',
        'image_mode': 'Image',
        'enter_answers_instruction': 'Enter the correct answers and grading criteria here. The AI will use this to grade student submissions.',
        'save_text': 'Save Text',
        'student_submissions': 'Student Submissions',
        'upload_answer_sheets': 'Upload Answer Sheets',
        'total_uploaded': 'Total Uploaded',
        'graded_count_label': 'Graded',
        'ai_auto_grading': 'AI Auto-Grading',
        'ai_grading_subtitle': 'Start the automated grading process using Gemini AI. This compares student answers with your model answer.',
        'start_grading_now': 'Start Grading Now',
        'upload_submissions_first': 'Upload Submissions First',
        'enter_model_answer_first': 'Enter Model Answer First',
        'no_submissions_uploaded': 'No answer sheets uploaded yet.',
        'upload_pdf_hint': 'Upload a PDF file containing the model answer. AI will compare student handwritten answers with this PDF.',
        'upload_image_hint': 'Upload an image containing the model answer. AI will compare student handwritten answers with this image.',
        'choose_pdf': 'Choose PDF File',
        'choose_image': 'Choose Image File',
        'delete_btn': 'Delete',
        'view_pdf_btn': 'View PDF',
        'view_image_btn': 'View Image',
        'grading_in_progress': 'Grading in progress...',
        'upload_pdf_title': 'Upload Model Answer PDF',
        'upload_image_title': 'Upload Model Answer Image',
        'click_to_browse': 'Click to browse or drag and drop',
        'max_file_size': 'Max file size: 10MB',
        'all_graded_alert': 'All submissions are already graded!',
        'delete_submission_confirm': 'Are you sure you want to delete this submission?',
        'delete_submission_fail': 'Failed to delete submission',
        'grading_error_msg': 'An error occurred during grading.',

        // Bulk Upload
        'drop_sheets_here': 'Drop Answer Sheets Here',
        'or_click_to_browse': 'or click to browse files',
        'select_files': 'Select Files',
        'supported_formats_hint': 'Supported: JPG, PNG, PDF • Max 10MB per file',
        'files_count': 'Files',
        'grouped_with_page': 'Grouped with Page',
        'close': 'Close',
        'upload_all': 'Upload All',
        'ai_detecting_info': 'AI is detecting Student Info...',
        'enter_student_id': 'Enter Student ID',
        'enter_student_name': 'Enter Student Name',
        'verified_student': 'Verified',
        'same_as_above': 'Same as above',
        'copy_student_prev': 'Copy student from previous page',
        'uploaded_status': 'Uploaded',
        'assign_students_error': 'Please assign students to all files before uploading',

        // Grade Detail Modal
        'student_name': 'Student Name',
        'student_id': 'Student ID',
        'save_details': 'Save Details',
        'edit_student_details': 'Edit Student Details',
        'edit_ai_grade': 'Edit AI Grade',
        'grade_label': 'Grade',
        'ai_analysis_insights': 'AI Analysis & Insights',
        'paper_vs_model': 'Paper vs Model Answer',
        'ai_confidence_score': 'AI Confidence Score',
        'ai_confidence_desc': 'The AI is {confidence}% confident in this grading based on clarity of handwriting and match with the model answer.',
        'detailed_feedback': 'Detailed Feedback',
        'what_went_well': 'What Went Well',
        'no_strengths_highlighted': 'No specific strengths highlighted.',
        'areas_for_improvement': 'Areas for Improvement',
        'no_errors_found': 'No specific errors found.',
        'student_answer': "Student's Answer",
        'page_of': 'Page {current} of {total}',
        'open_original': 'Open Original',
        'failed_to_load_image': 'Failed to load image',
        'no_image_available': 'No image available',
        'model_answer': 'Model Answer',
        'model_answer_pdf_desc': 'Model answer is a PDF document.',
        'view_pdf_model_answer': 'View PDF Model Answer',
        'no_model_answer_provided': 'No model answer provided.',
        'failed_to_update_score': 'Failed to update score.',
        'failed_to_update_details': 'Failed to update student details.',

        // Grade Analytics
        'pass_rate_overview': 'Pass Rate Overview',
        'score_performance_ranges': 'Score Performance Ranges',

        // Grade Sheet
        'back_to_exam_detail': 'Back to Exam Detail',
        'grade_report_analytics': 'Grade Report & Performance Analytics',
        'hide_analytics': 'Hide Analytics',
        'show_analytics': 'Show Analytics',
        'export_excel': 'Export Excel',
        'export_pdf': 'Export PDF',
        'publish_all': 'Publish All',
        'class_average': 'Class Average',
        'passed_count': 'Passed',
        'failed_count': 'Failed',
        'enrolled': 'Enrolled',
        'search_by_name_id': 'Search by name or ID...',
        'all_status': 'All Status',
        'published': 'Published',
        'all_grades': 'All Grades',
        'passing_status': 'Passing',
        'failing_status': 'Failing',
        'table_student': 'Student',
        'table_score': 'Score',
        'table_performance': 'Performance',
        'table_grade': 'Grade',
        'table_status': 'Status',
        'table_actions': 'Actions',
        'unpublish_result': 'Unpublish Result',
        'publish_result': 'Publish Result',
        'view_detailed_analysis': 'View Detailed Analysis',
        'delete_record': 'Delete Record',
        'no_students_found': 'No students found',
        'adjust_filters_desc': 'Adjust your filters to see results.',
        'loading_grades': 'Loading Grades...',
        'no_grade_data_found': 'No Grade Data Found',
        'no_grade_data_desc': 'There are no grades available for this exam yet. Please start grading submissions first.',
        'results_published_alert': 'All results have been published successfully!',
        'publish_all_confirm': 'Are you sure you want to publish all {count} unpublished results? This will make them visible to students.',
        'publish_all_already': 'All results are already published!',
        'publish_all_fail': 'Failed to publish some results.',
        'publish_grade_confirm': 'Are you sure you want to {action} this result?',
        'publish_grade_fail': 'Failed to update grade status.',
        'delete_grade_confirm': 'Are you sure you want to completely delete the record and submission for {name}?',
        'delete_grade_fail': 'Failed to delete grade record.',

        // Students & Performance
        'academic_performance': 'Academic Performance',
        'students_overview': 'Students Overview',
        'students_overview_desc': 'Monitor student performance, track progress across courses, and view detailed academic profiles.',
        'top_performers': 'Top Performers (90%+)',
        'need_support': 'Need Support (<60%)',
        'search_students_placeholder': 'Search students by name or ID...',
        'no_students_found_desc_search': 'Try adjusting your search terms.',
        'no_students_found_desc_default': 'Students will appear here once you have graded their exams.',
        'courses': 'Courses',
        'avg_grade': 'Avg Grade',
        'click_view_performance': 'Click to view performance',
        'back_to_students': 'Back to Students',
        'no_academic_records': 'No Academic Records',
        'no_graded_exams_yet': 'This student has no graded exams yet.',
        'highest_grade': 'Highest',
        'average_label': 'Average',
        'performance_trend': 'Performance Trend',
        'recent_assessments': 'Recent Assessments',
        'score_percentage': 'Score (%)',

        // Profile Page
        'change_avatar': 'Change',
        'remove_photo': 'Remove Photo',
        'edit_profile': 'Edit Profile',
        'account_status': 'Account Status',
        'member_since': 'Member Since',
        'personal_information': 'Personal Information',
        'update_details_subtitle': 'Update your details below.',
        'personal_info_subtitle': 'Your personal and academic details.',
        'full_name': 'Full Name',
        'department': 'Department',
        'academic_rank': 'Academic Rank',
        'specialization': 'Specialization',
        'save_changes': 'Save Changes',
        'error_loading_profile': 'Error loading profile data',
        'profile_updated_success': 'Profile updated successfully',
        'failed_save_changes': 'Failed to save changes',
        'photo_updated_success': 'Profile photo updated',
        'failed_upload_photo': 'Failed to upload photo',
        'photo_removed_success': 'Profile photo removed',
        'failed_remove_photo': 'Failed to remove photo',
        'remove_photo_confirm': 'Are you sure you want to remove your profile photo?',
        'Professor': 'Professor',
        'Associate Professor': 'Associate Professor',
        'Assistant Professor': 'Assistant Professor',
        'Lecturer': 'Lecturer',
        'Teaching Assistant': 'Teaching Assistant',
        'faculty_of_bis': 'Faculty of BIS',

        // Settings Page
        'theme_preferences': 'Theme Preferences',
        'interface_font_size': 'Interface Font Size',
        'compact': 'Compact',
        'default': 'Default',
        'comfortable': 'Comfortable',
        'high_contrast_desc': 'Increase distinctness between elements',
        'reduced_motion_desc': 'Minimize animations and movement',
        'united_states': 'United States',
        'egypt': 'Egypt',
        'notification_preferences': 'Notification Preferences',
        'email_notifications_desc': 'Receive daily summaries, grading reports, and important updates via email.',
        'push_notifications_desc': 'Get real-time browser alerts for new submissions and system messages.',
        'security_settings': 'Security Settings',
        'password_auth': 'Password & Authentication',
        'password_auth_desc': 'Manage your password and sign-in methods.',
        'change_password_desc': 'Send a reset link to your email',
        'theme_set_success': 'Theme set to {theme}',
        'font_size_updated': 'Font size updated',
        'high_contrast_enabled': 'High Contrast Enabled',
        'high_contrast_disabled': 'High Contrast Disabled',
        'reduced_motion_enabled': 'Reduced Motion Enabled',
        'reduced_motion_disabled': 'Reduced Motion Disabled',
        'browser_not_support_notifications': 'This browser does not support desktop notifications',
        'notification_permission_denied': 'Notification permission denied by user',
        'push_notifications_enabled': 'Push notifications enabled!',
        'test_notification_title': 'Test Notification',
        'test_notification_body': 'Notifications are working!',
        'email_notifications_enabled': 'Email notifications enabled',
        'email_notifications_disabled': 'Email notifications disabled',
        'push_notifications_disabled': 'Push notifications disabled',
        'password_reset_sent': 'Password reset link sent to {email}',
        'sign_out_success': 'Signed out successfully'
    },
    ar: {
        // Sidebar
        'overview': 'نظرة عامة',
        'profile': 'الملف الشخصي',
        'exams': 'الامتحانات',
        'my_courses': 'موادي الدراسية',
        'students': 'الطلاب',
        'settings': 'الإعدادات',
        'sign_out': 'تسجيل خروج',
        'smart_grader': 'E-WRITTEN',
        'faculty_space': 'مساحة أعضاء هيئة التدريس',
        'main': 'الرئيسية',
        'academic': 'أكاديمي',
        'account': 'الحساب',
 
        // Dashboard Home
        'academic_dashboard': 'لوحة القيادة الأكاديمية',
        'welcome_back': 'أهلاً بك يا دكتور.',
        'active_courses': 'الدورات النشطة',
        'total_students': 'إجمالي الطلاب',
        'pending_papers': 'أوراق قيد الانتظار',
        'graded_this_week': 'تم تصحيحها هذا الأسبوع',
        'average_grade': 'متوسط الدرجات',
        'grade_distribution': 'توزيع الدرجات',
        'pass_fail_analysis': 'تحليل النجاح والرسوب',
        'passed': 'ناجح',
        'failed': 'راسب',
        'view_all': 'عرض الكل',
        'academic_year': 'العام الأكاديمي 2025-2026',
        'welcome_back_name': 'مرحباً بك مجدداً،',
        'dashboard_title': 'لوحة التحكم',
        'active_exams': 'الامتحانات النشطة',
        'new_grades': 'الدرجات الجديدة',
        'avg_score': 'متوسط النتائج',
        'at_risk': 'حالات التعثر',
        'overall_performance_curve': 'منحنى الأداء العام',
        'pass_fail_ratio': 'نسبة النجاح مقابل الرسوب',
        'pass_rate': 'معدل النجاح',
        'no_description': 'لا يوجد وصف للمادة.',
        'credits': 'ساعة معتمدة',
        'students_count': 'طالب',
 
        // Settings
        'settings_title': 'الإعدادات والتفضيلات',
        'settings_subtitle': 'قم بتخصيص مساحة العمل الخاصة بك.',
        'appearance': 'المظهر',
        'theme': 'السمة',
        'light': 'فاتح',
        'dark': 'داكن',
        'system': 'النظام',
        'accessibility': 'إمكانية الوصول',
        'font_size': 'حجم الخط',
        'high_contrast': 'تباين عالي',
        'reduced_motion': 'تقليل الحركة',
        'language_region': 'اللغة والمنطقة',
        'notifications': 'الإشعارات',
        'security': 'الأمان وتسجيل الدخول',
        'change_password': 'تغيير كلمة المرور',
        'danger_zone': 'منطقة الخطر',
        'email_notifications': 'إشعارات البريد الإلكتروني',
        'push_notifications': 'الإشعارات الفورية',

        // Exams Management
        'back_to_overview': 'العودة للرئيسية',
        'examinations': 'الامتحانات',
        'exams_manager': 'إدارة الامتحانات',
        'exams_subtitle': 'قم بجدولة وإدارة ومتابعة جميع تقييمات مقرراتك الدراسية في مكان واحد.',
        'create_new_exam': 'إنشاء امتحان جديد',
        'total_exams': 'إجمالي الامتحانات',
        'upcoming': 'قادمة',
        'completed': 'مكتملة',
        'with_model_answers': 'بنموذج إجابة',
        'search_exams_placeholder': 'ابحث باسم الامتحان، كود المقرر...',
        'all_types': 'جميع الأنواع',
        'midterm': 'ميدتيرم',
        'final': 'نهائي',
        'quiz': 'اختبار قصير',
        'assignment': 'تكليف',
        'model_answer_attached': 'نموذج الإجابة مرفق',
        'no_model_answer': 'لا يوجد نموذج إجابة',
        'view_details': 'عرض التفاصيل',
        'draft': 'مسودة',
        'scheduled': 'مجدول',
        'ongoing': 'جارٍ الآن',
        'graded': 'تم رصد الدرجات',
        'pending': 'قيد الانتظار',
        'processing': 'جاري التصحيح',
        'no_exams_found': 'لم يتم العثور على امتحانات',
        'no_exams_created': 'لم يتم إنشاء امتحانات بعد',
        'no_exams_found_desc': 'لم نجد أي امتحانات تطابق معايير البحث الحالية. جرب تعديل البحث أو التصفية.',
        'no_exams_created_desc': 'ابدأ بإنشاء امتحانك الأول. يمكنك تحديد التفاصيل والمدة ورفع نموذج الإجابة لاحقًا.',
        'create_first_exam': 'أنشئ امتحانك الأول',

        // Create Exam Modal
        'create_exam_subtitle': 'قم بإعداد تفاصيل الامتحان ورفع نموذج الإجابة لاحقًا',
        'course_label': 'المقرر الدراسي *',
        'select_course_placeholder': 'اختر مقررًا',
        'exam_title_label': 'عنوان الامتحان *',
        'exam_title_placeholder': 'مثال: امتحان منتصف الفصل - خريف 2026',
        'exam_type_label': 'نوع الامتحان *',
        'exam_date_label': 'تاريخ ووقت الامتحان *',
        'exam_duration_label': 'المدة (بالدقائق) *',
        'exam_marks_label': 'الدرجة الكلية *',
        'multi_page_label': 'امتحان متعدد الصفحات',
        'cancel': 'إلغاء',
        'create_exam_button': 'إنشاء الامتحان',
        'exam_date_future_error': 'يجب أن يكون تاريخ الامتحان في المستقبل',
        'fill_required_error': 'يرجى ملء جميع الحقول المطلوبة',

        // Exam Detail
        'back_to_exams': 'العودة للامتحانات',
        'view_results': 'عرض النتائج',
        'model_answer_rubric': 'نموذج الإجابة / معايير التصحيح',
        'text_mode': 'نص',
        'pdf_mode': 'ملف PDF',
        'image_mode': 'صورة',
        'enter_answers_instruction': 'أدخل الإجابات الصحيحة ومعايير التصحيح هنا. سيستخدم الذكاء الاصطناعي هذا لتصحيح إجابات الطلاب.',
        'save_text': 'حفظ النص',
        'student_submissions': 'إجابات الطلاب',
        'upload_answer_sheets': 'رفع أوراق الإجابة',
        'total_uploaded': 'إجمالي المرفوع',
        'graded_count_label': 'المصححة',
        'ai_auto_grading': 'التصحيح التلقائي بالذكاء الاصطناعي',
        'ai_grading_subtitle': 'ابدأ عملية التصحيح التلقائي باستخدام Gemini AI. سيقوم هذا بمقارنة إجابات الطلاب مع نموذج الإجابة الخاص بك.',
        'start_grading_now': 'ابدأ التصحيح الآن',
        'upload_submissions_first': 'ارفع إجابات الطلاب أولاً',
        'enter_model_answer_first': 'أدخل نموذج الإجابة أولاً',
        'no_submissions_uploaded': 'لا توجد تسليمات مرفوعة بعد.',
        'upload_pdf_hint': 'قم برفع ملف PDF يحتوي على نموذج الإجابة. سيقوم الذكاء الاصطناعي بمقارنة إجابات الطلاب المكتوبة بخط اليد مع هذا الملف.',
        'upload_image_hint': 'قم برفع صورة تحتوي على نموذج الإجابة. سيقوم الذكاء الاصطناعي بمقارنة إجابات الطلاب المكتوبة بخط اليد مع هذه الصورة.',
        'choose_pdf': 'اختر ملف PDF',
        'choose_image': 'اختر ملف صورة',
        'delete_btn': 'حذف',
        'view_pdf_btn': 'عرض ملف PDF',
        'view_image_btn': 'عرض الصورة',
        'grading_in_progress': 'جاري التصحيح الآن...',
        'upload_pdf_title': 'رفع نموذج إجابة PDF',
        'upload_image_title': 'رفع نموذج إجابة صورة',
        'click_to_browse': 'انقر للتصفح أو اسحب وأفلت الملف',
        'max_file_size': 'الحد الأقصى لحجم الملف: ١٠ ميجابايت',
        'all_graded_alert': 'تم تصحيح جميع الإجابات بالفعل!',
        'delete_submission_confirm': 'هل أنت متأكد من حذف هذا التسليم؟',
        'delete_submission_fail': 'فشل حذف التسليم',
        'grading_error_msg': 'حدث خطأ أثناء التصحيح.',

        // Bulk Upload
        'drop_sheets_here': 'قم بإفلات أوراق الإجابة هنا',
        'or_click_to_browse': 'أو انقر لتصفح الملفات',
        'select_files': 'اختر الملفات',
        'supported_formats_hint': 'الامتدادات المدعومة: JPG, PNG, PDF • الحد الأقصى لكل ملف ١٠ ميجابايت',
        'files_count': 'الملفات',
        'grouped_with_page': 'مجمع مع الصفحة',
        'close': 'إغلاق',
        'upload_all': 'رفع الكل',
        'ai_detecting_info': 'الذكاء الاصطناعي يستخرج بيانات الطالب...',
        'enter_student_id': 'أدخل الرقم التعريفي للطالب',
        'enter_student_name': 'أدخل اسم الطالب',
        'verified_student': 'تم التحقق',
        'same_as_above': 'نفس الطالب أعلاه',
        'copy_student_prev': 'نسخ بيانات الطالب من الصفحة السابقة',
        'uploaded_status': 'تم الرفع',
        'assign_students_error': 'يرجى تحديد بيانات الطلاب لجميع الملفات قبل الرفع',

        // Grade Detail Modal
        'student_name': 'اسم الطالب',
        'student_id': 'الرقم التعريفي للطالب',
        'save_details': 'حفظ البيانات',
        'edit_student_details': 'تعديل بيانات الطالب',
        'edit_ai_grade': 'تعديل درجة الذكاء الاصطناعي',
        'grade_label': 'التقدير',
        'ai_analysis_insights': 'تحليل الذكاء الاصطناعي ورؤى الأداء',
        'paper_vs_model': 'ورقة الإجابة مقابل نموذج الإجابة',
        'ai_confidence_score': 'درجة ثقة الذكاء الاصطناعي',
        'ai_confidence_desc': 'الذكاء الاصطناعي واثق بنسبة {confidence}% من هذا التصحيح بناءً على وضوح الخط والمطابقة مع نموذج الإجابة.',
        'detailed_feedback': 'ملاحظات تفصيلية',
        'what_went_well': 'نقاط القوة',
        'no_strengths_highlighted': 'لم يتم تحديد نقاط قوة محددة.',
        'areas_for_improvement': 'نقاط تحتاج لتحسين',
        'no_errors_found': 'لم يتم العثور على أخطاء محددة.',
        'student_answer': 'إجابة الطالب',
        'page_of': 'صفحة {current} من {total}',
        'open_original': 'فتح الورقة الأصلية',
        'failed_to_load_image': 'فشل تحميل الصورة',
        'no_image_available': 'لا توجد صورة متاحة',
        'model_answer': 'نموذج الإجابة',
        'model_answer_pdf_desc': 'نموذج الإجابة عبارة عن ملف PDF.',
        'view_pdf_model_answer': 'عرض نموذج الإجابة PDF',
        'no_model_answer_provided': 'لم يتم توفير نموذج إجابة.',
        'failed_to_update_score': 'فشل تحديث الدرجة.',
        'failed_to_update_details': 'فشل تحديث بيانات الطالب.',

        // Grade Analytics
        'pass_rate_overview': 'نظرة عامة على معدل النجاح',
        'score_performance_ranges': 'نطاقات أداء الدرجات',

        // Grade Sheet
        'back_to_exam_detail': 'العودة لتفاصيل الامتحان',
        'grade_report_analytics': 'تقرير الدرجات وتحليلات الأداء',
        'hide_analytics': 'إخفاء التحليلات',
        'show_analytics': 'عرض التحليلات',
        'export_excel': 'تصدير إكسل',
        'export_pdf': 'تصدير PDF',
        'publish_all': 'نشر الكل',
        'class_average': 'متوسط الفصل',
        'passed_count': 'ناجح',
        'failed_count': 'راسب',
        'enrolled': 'مسجل',
        'search_by_name_id': 'ابحث بالاسم أو الرقم التعريفي...',
        'all_status': 'جميع الحالات',
        'published': 'تم النشر',
        'all_grades': 'جميع الدرجات',
        'passing_status': 'ناجح',
        'failing_status': 'راسب',
        'table_student': 'الطالب',
        'table_score': 'الدرجة',
        'table_performance': 'الأداء',
        'table_grade': 'التقدير',
        'table_status': 'الحالة',
        'table_actions': 'إجراءات',
        'unpublish_result': 'إلغاء نشر النتيجة',
        'publish_result': 'نشر النتيجة',
        'view_detailed_analysis': 'عرض التحليل التفصيلي',
        'delete_record': 'حذف السجل',
        'no_students_found': 'لم يتم العثور على طلاب',
        'adjust_filters_desc': 'قم بتعديل عوامل التصفية لعرض النتائج.',
        'loading_grades': 'جاري تحميل الدرجات...',
        'no_grade_data_found': 'لم يتم العثور على درجات',
        'no_grade_data_desc': 'لا توجد درجات متاحة لهذا الامتحان بعد. يرجى البدء بتصحيح إجابات الطلاب أولاً.',
        'results_published_alert': 'تم نشر جميع النتائج بنجاح!',
        'publish_all_confirm': 'هل أنت متأكد من نشر جميع النتائج غير المنشورة (عدد: {count})؟ سيؤدي هذا لجعلها مرئية للطلاب.',
        'publish_all_already': 'تم نشر جميع النتائج بالفعل!',
        'publish_all_fail': 'فشل نشر بعض النتائج.',
        'publish_grade_confirm': 'هل أنت متأكد من {action} هذه النتيجة؟',
        'publish_grade_fail': 'فشل تحديث حالة الدرجة.',
        'delete_grade_confirm': 'هل أنت متأكد من حذف السجل والتسليم الخاص بالطالب {name} نهائياً؟',
        'delete_grade_fail': 'فشل حذف سجل الدرجة.',

        // Students & Performance
        'academic_performance': 'الأداء الأكاديمي',
        'students_overview': 'نظرة عامة على الطلاب',
        'students_overview_desc': 'مراقبة أداء الطلاب، وتتبع التقدم عبر المقررات، وعرض الملفات الأكاديمية التفصيلية.',
        'top_performers': 'الطلاب المتفوقين (90%+)',
        'need_support': 'يحتاجون لدعم (<60%)',
        'search_students_placeholder': 'ابحث عن الطلاب بالاسم أو الرقم التعريفي...',
        'no_students_found_desc_search': 'حاول تعديل كلمات البحث.',
        'no_students_found_desc_default': 'سيظهر الطلاب هنا بمجرد رصد درجات امتحاناتهم.',
        'courses': 'المقررات',
        'avg_grade': 'متوسط الدرجة',
        'click_view_performance': 'انقر لعرض الأداء الأكاديمي',
        'back_to_students': 'العودة للطلاب',
        'no_academic_records': 'لا توجد سجلات أكاديمية',
        'no_graded_exams_yet': 'هذا الطالب ليس لديه أي امتحانات مصححة بعد.',
        'highest_grade': 'الدرجة الأعلى',
        'average_label': 'المتوسط',
        'performance_trend': 'منحنى الأداء',
        'recent_assessments': 'التقييمات الأخيرة',
        'score_percentage': 'النتيجة (%)',

        // Profile Page
        'change_avatar': 'تغيير',
        'remove_photo': 'إزالة الصورة',
        'edit_profile': 'تعديل الملف الشخصي',
        'account_status': 'حالة الحساب',
        'member_since': 'عضو منذ',
        'personal_information': 'البيانات الشخصية',
        'update_details_subtitle': 'قم بتحديث بياناتك أدناه.',
        'personal_info_subtitle': 'تفاصيل بياناتك الشخصية والأكاديمية.',
        'full_name': 'الاسم الكامل',
        'department': 'القسم',
        'academic_rank': 'الدرجة العلمية',
        'specialization': 'التخصص',
        'save_changes': 'حفظ التغييرات',
        'error_loading_profile': 'خطأ في تحميل بيانات الملف الشخصي',
        'profile_updated_success': 'تم تحديث الملف الشخصي بنجاح',
        'failed_save_changes': 'فشل حفظ التغييرات',
        'photo_updated_success': 'تم تحديث صورة الملف الشخصي',
        'failed_upload_photo': 'فشل رفع الصورة',
        'photo_removed_success': 'تم إزالة صورة الملف الشخصي',
        'failed_remove_photo': 'فشل إزالة الصورة',
        'remove_photo_confirm': 'هل أنت متأكد من رغبتك في إزالة صورة الملف الشخصي؟',
        'Professor': 'أستاذ دكتور',
        'Associate Professor': 'أستاذ مساعد',
        'Assistant Professor': 'أستاذ مساعد (مدرس)',
        'Lecturer': 'مدرس مساعد',
        'Teaching Assistant': 'معيد',
        'faculty_of_bis': 'برنامج نظم معلومات الأعمال',

        // Settings Page
        'theme_preferences': 'تفضيلات المظهر',
        'interface_font_size': 'حجم خط الواجهة',
        'compact': 'مدمج',
        'default': 'افتراضي',
        'comfortable': 'مريح',
        'high_contrast_desc': 'زيادة التباين ووضوح العناصر',
        'reduced_motion_desc': 'تقليل التأثيرات البصرية والحركة',
        'united_states': 'الولايات المتحدة',
        'egypt': 'مصر',
        'notification_preferences': 'تفضيلات الإشعارات',
        'email_notifications_desc': 'تلقي ملخصات يومية، تقارير رصد الدرجات، والتحديثات الهامة عبر البريد الإلكتروني.',
        'push_notifications_desc': 'الحصول على تنبيهات فورية في المتصفح للتسليمات الجديدة ورسائل النظام.',
        'security_settings': 'إعدادات الأمان',
        'password_auth': 'كلمة المرور والمصادقة',
        'password_auth_desc': 'إدارة كلمة المرور وطرق تسجيل الدخول الخاصة بك.',
        'change_password_desc': 'إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني',
        'theme_set_success': 'تم تعيين المظهر إلى {theme}',
        'font_size_updated': 'تم تحديث حجم الخط بنجاح',
        'high_contrast_enabled': 'تم تفعيل التباين العالي',
        'high_contrast_disabled': 'تم إلغاء تفعيل التباين العالي',
        'reduced_motion_enabled': 'تم تفعيل تقليل الحركة',
        'reduced_motion_disabled': 'تم إلغاء تفعيل تقليل الحركة',
        'browser_not_support_notifications': 'هذا المتصفح لا يدعم إشعارات سطح المكتب',
        'notification_permission_denied': 'تم رفض إذن الإشعارات من قبل المستخدم',
        'push_notifications_enabled': 'تم تفعيل الإشعارات الفورية!',
        'test_notification_title': 'إشعار تجريبي',
        'test_notification_body': 'الإشعارات تعمل بنجاح!',
        'email_notifications_enabled': 'تم تفعيل إشعارات البريد الإلكتروني',
        'email_notifications_disabled': 'تم تعطيل إشعارات البريد الإلكتروني',
        'push_notifications_disabled': 'تم تعطيل الإشعارات الفورية',
        'password_reset_sent': 'تم إرسال رابط إعادة تعيين كلمة المرور إلى {email}',
        'sign_out_success': 'تم تسجيل الخروج بنجاح'
    },
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        const savedLang = (localStorage.getItem('language') as Language) || 'en';
        setLanguageState(savedLang);
        document.documentElement.lang = savedLang;
        document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr';
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
        document.documentElement.lang = lang;
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, dir: language === 'ar' ? 'rtl' : 'ltr' }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
